[book]
authors = ["DasLixou", "Backlang Org", "furesoft"]
language = "en"
multilingual = false
src = "src"
title = "Learn BackLang"

[output.html]
additional-js = ["theme/custom-highlight.js"]
additional-css = ["./theme/catppuccin.css", "./theme/catppuccin-highlight.css"]
cname = "learn.backlang.org"
git-repository-url = "https://github.com/Backlang-Org/Backlang"
edit-url-template = "https://github.com/Backlang-Org/learn/edit/main/{path}"

[preprocessor.footnote]
[preprocessor.quiz]