[[questions]]
type = "MultipleChoice"
prompt.prompt = "Is `x and !b` valid code?"
prompt.choices = [
  "Yes",
  "No",
]
answer.answer = 0

[[questions]]
type = "MultipleChoice"
prompt.prompt = "When is `x and !b` not valid code?"
prompt.choices = [
  "When the variable x is the same type as variable b",
  "If the type of those variables is not bool or don't has overloaded operators",
]
answer.answer = 1
