[[questions]]
type = "ShortAnswer"
prompt.prompt = "What is the difference between a struct and a tuple."
answer.answer = "name"

[[questions]]
type = "MultipleChoice"
prompt.prompt = "Is it possible to nest tuples?"
prompt.choices = [
  "Yes",
  "No",
]
answer.answer = 0

[[questions]]
type = "MultipleChoice"
prompt.prompt = "How many values can be contained in a tuple?"
prompt.choices = [
  "2",
  "4",
  "6",
  "8",
  "16"
]
answer.answer = 3

[[questions]]
type = "MultipleChoice"
prompt.prompt = "Can a `char` be implicitly cast to an `i16`"
prompt.choices = [
  "Yes",
  "No",
]
answer.answer = 1

[[questions]]
type = "MultipleChoice"
prompt.prompt = "If you declared a variable with an unit of measure type, could you implicitly cast it to another measure type?"
prompt.choices = [
  "Yes",
  "No",
]
answer.answer = 1