name: Deploy Documentation

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v3

      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable

      - name: Setup | mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: "latest"

      - name: Setup | mdBook Extensions
        run: |
          cargo install mdbook-quiz
          cargo install mdbook-footnote
          cargo install mdbook-sitemap-generator

      - name: Build | mdBook build html
        run: mdbook build

      - name: Build | Generate sitemap.xml
        run: mdbook-sitemap-generator -d learn.backlang.org -o book/sitemap.xml

      - name: Deploy | Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
          publish_branch: gh-pages
